services:
  web:
    build: .
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8000
    volumes:
      - ./app/migrations/versions:/app/app/migrations/versions
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: ./uv.lock
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
