services:
  web:
    build: .
    command: fastapi dev app/main.py --port 8000
    # volumes:
    #   - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi

volumes:
  postgres_data:
  index_data:
    driver: local
