name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build . -t fastapi:latest

      - name: Run tests
        run: docker run fastapi:latest pytest
